
CREATE TABLE CLIENTE(
DNI  CHAR(8) PRIMARY KEY,
NOMBRE  VARCHAR2(35) NOT NULL,
APELLIDO VARCHAR(35) NOT NULL,
EMAIL VARCHAR2(40) NOT NULL,
TELEFONO NUMBER
);

SELECT * FROM CLIENTE;


 CREATE OR REPLACE PROCEDURE SP_INSERT_CLIENTE(
 P_DNI IN CLIENTE.DNI%TYPE,
 P_NOMBRE IN  CLIENTE.NOMBRE%TYPE,
 P_APELLIDO IN CLIENTE.APELLIDO%TYPE,
 P_EMAIL IN CLIENTE.EMAIL%TYPE,
 P_TELEFONO IN CLIENTE.TELEFONO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   INSERT INTO CLIENTE VALUES(P_DNI,P_NOMBRE,P_APELLIDO,P_EMAIL,P_TELEFONO);
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL INSERTAR'; 
        ROLLBACK; 
 END;
 
  CREATE OR REPLACE PROCEDURE SP_UPDATE_CLIENTE(
 P_DNI IN CLIENTE.DNI%TYPE,
 P_NOMBRE IN  CLIENTE.NOMBRE%TYPE,
 P_APELLIDO IN CLIENTE.APELLIDO%TYPE,
 P_EMAIL IN CLIENTE.EMAIL%TYPE,
 P_TELEFONO IN CLIENTE.TELEFONO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE CLIENTE
   SET NOMBRE = P_NOMBRE, APELLIDO=P_APELLIDO,EMAIL=P_EMAIL,TELEFONO=P_TELEFONO
   WHERE DNI= P_DNI;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
 
 
 CREATE OR REPLACE PROCEDURE SP_DELETE_CLIENTE(
  P_DNI IN CLIENTE.DNI%TYPE,
   P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM CLIENTE
   WHERE DNI = P_DNI;
  P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          P_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;
 
 CREATE OR REPLACE PROCEDURE SP_SELECT_CLIENTE(
 P_CURSOR OUT  SYS_REFCURSOR
 )
 AS
 BEGIN
   OPEN P_CURSOR FOR
   SELECT DNI,NOMBRE,APELLIDO,EMAIL,TELEFONO   
    FROM CLIENTE;
 
   END;
   
INSERT INTO  CLIENTE  VALUES ('16325896','A','B','C',321654987);
   
insert into ALUMNO (DNI, NOMBRE, APELLIDO, DIRECCION, EDAD)
values ('15962365', 'JUAN PERES', 'RAMOS', 'AV.LOS JASMINES 254', 15);

insert into ALUMNO (DNI, NOMBRE, APELLIDO, DIRECCION, EDAD)
values ('15962366', 'JUAN PERES', 'RAMOS', 'AV.LOS JASMINES 254', 16);

insert into ALUMNO (DNI, NOMBRE, APELLIDO, DIRECCION, EDAD)
values ('15962367', 'JUAN PERES', 'RAMOS', 'AV.LOS JASMINES 254', 17);

insert into ALUMNO (DNI, NOMBRE, APELLIDO, DIRECCION, EDAD)
values ('15962368', 'JUAN PERES', 'RAMOS', 'AV.LOS JASMINES 254', 18);

insert into ALUMNO (DNI, NOMBRE, APELLIDO, DIRECCION, EDAD)
values ('15962369', 'JUAN PERES', 'RAMOS', 'AV.LOS JASMINES 254', 19);

insert into ALUMNO (DNI, NOMBRE, APELLIDO, DIRECCION, EDAD)
values ('15962370', 'JUAN PERES', 'RAMOS', 'AV.LOS JASMINES 254', 20);

   



SELECT * FROM CLIENTE
SELECT * FROM EMPLEADOS;
   
   
   
SELECT dni,nombre,apellido,direccion,edad
FROM alumno
WHERE edad > 17
ORDER BY nombre DESC;

SELECT dni,nombre,apellido,direccion,edad
FROM alumno
WHERE edad > 17
ORDER BY nombre ;

SELECT dni,nombre,apellido,direccion,edad
FROM alumno
WHERE edad > 17
ORDER BY 1 ;

SELECT dni,nombre || ' ' || apellido nomcol,direccion,edad
FROM alumno
WHERE edad > 17
ORDER BY nomcol ;


 
